import string
print(string.ascii_lowercase)
print(string.ascii_uppercase)
print(string.ascii_letters)
print(string.digits)
print(string.punctuation)
print(string.whitespace)
print(string.printable)
print(string.hexdigits)
print(string.octdigits)
print(string.ascii_letters + string.digits)
print(string.ascii_letters + string.digits + string.punctuation)
print(string.ascii_letters + string.digits + string.punctuation + string.whitespace)
print(string.ascii_letters + string.digits + string.punctuation + string.whitespace + string.ascii_letters)
print(string.ascii_letters + string.digits + string.punctuation + string.whitespace + string.ascii_letters + string.digits)